version: '3.3'
services:
  server:
    build: ./server
    restart: unless-stopped
    container_name: api_backend
    extra_hosts:
      - "10.128.0.4:5000"
    ports:
      - '5000:5000'
    networks:
      - shared-network
  client:
    stdin_open: true
    build: ./client
    container_name: app_frontend
    extra_hosts:
      - "10.128.0.4:4000"
    ports:
      - '4000:4000'
    networks:
      - shared-network
    depends_on:
      - server
networks:
  shared-network:
    driver: bridge
