---
version: "3"
services:
  backend:
    build:
      context: ./server
    container_name: backend
    ports:
      - 5000:5000
    environment:
      MONGO_URI: mongodb+srv://rimkhedher:rimkhedher123123@atlascluster.2kib5iz.mongodb.net/test
      networks:
        - my-network
  frontend:
    build:
      context: ./client
    container_name: frontend
    ports:
      - 3000:3000
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
