version: '3.3'
services:
  server:
    build: ./server
    restart: unless-stopped
    container_name: api_backend
    ports:
      - '5000:5000'
    networks:
      - shared-network
  client:
    stdin_open: true
    build: ./client
    container_name: app_frontend
    ports:
      - '4000:4000'
    extra_hosts:
      - "104.197.89.109:4000"  
    networks:
      - shared-network
    depends_on:
      - server
networks:
  shared-network:
    driver: bridge
