version: '3.8'
services:
  server:
    build: ./server
    restart: unless-stopped
    container_name: api_backend
    ports:
      - '3000:3000'
    networks:
      - shared-network
  client:
    stdin_open: true
    build: ./client
    container_name: app_frontend
    ports:
      - '80:3000'
    networks:
      - shared-network
    depends_on:
      - server
networks:
  shared-network:
